### ISSUE TITLE
Game Crashed in 1.12.2 Version

### ISSUE THREAD

**Issue by linfoxgamer** [DeflatedPickle/Minecraft-Beta-1.3-Unfix#2]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/1/21 9:28 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.util.math.RayTraceResult.getBlockPos()Lnet/minecraft/util/math/BlockPos;
	at com.deflatedpickle.squidmilk.SquidMilk.onItemRightClick(SquidMilk.kt:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_SquidMilk_onItemRightClick_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:469)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:43)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2265)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.deflatedpickle.squidmilk.SquidMilk.onItemRightClick(SquidMilk.kt:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_SquidMilk_onItemRightClick_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:469)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:43)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2265)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['lin_fox'/217, l='MpServer', x=-71.39, y=64.47, z=427.12]]
	Chunk stats: MultiplayerChunkCache: 616, 616
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-80,64,252), Chunk: (at 0,4,12 in -5,15; contains blocks -80,0,240 to -65,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5577 game time, 5577 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntitySheep['Sheep'/256, l='MpServer', x=-82.45, y=89.00, z=487.55], EntitySheep['Sheep'/257, l='MpServer', x=-85.50, y=88.00, z=485.50], EntityZombie['Zombie'/258, l='MpServer', x=-120.50, y=39.00, z=468.50], EntityCreeper['Creeper'/259, l='MpServer', x=-124.48, y=39.00, z=465.80], EntityCreeper['Creeper'/260, l='MpServer', x=-143.50, y=39.00, z=486.50], EntityCreeper['Creeper'/262, l='MpServer', x=-134.50, y=30.00, z=454.50], EntityCreeper['Creeper'/263, l='MpServer', x=-133.83, y=31.00, z=455.46], EntityCreeper['Creeper'/264, l='MpServer', x=-133.53, y=36.00, z=470.80], EntitySkeleton['Skeleton'/265, l='MpServer', x=-131.50, y=36.00, z=470.50], EntityCreeper['Creeper'/266, l='MpServer', x=-136.23, y=36.00, z=474.93], EntityBat['Bat'/268, l='MpServer', x=-124.67, y=39.64, z=468.36], EntitySkeleton['Skeleton'/531, l='MpServer', x=-30.50, y=58.00, z=499.73], EntityCreeper['Creeper'/787, l='MpServer', x=-137.50, y=31.00, z=473.50], EntityPig['Pig'/532, l='MpServer', x=-30.24, y=95.00, z=502.65], EntityPig['Pig'/533, l='MpServer', x=-19.50, y=93.00, z=502.50], EntityPig['Pig'/534, l='MpServer', x=-20.50, y=90.00, z=503.50], EntityZombie['Zombie'/790, l='MpServer', x=-104.50, y=30.00, z=421.50], EntityPig['Pig'/535, l='MpServer', x=-22.50, y=91.00, z=502.50], EntitySheep['Sheep'/543, l='MpServer', x=-4.26, y=69.00, z=453.59], EntityBat['Bat'/819, l='MpServer', x=-97.31, y=26.61, z=361.69], EntityBat['Bat'/820, l='MpServer', x=-93.47, y=23.69, z=361.62], EntityCow['Cow'/53, l='MpServer', x=-145.50, y=72.00, z=384.50], EntityBat['Bat'/821, l='MpServer', x=-85.73, y=26.66, z=354.04], EntityPlayerSP['lin_fox'/217, l='MpServer', x=-71.39, y=64.47, z=427.12], EntityCow['Cow'/54, l='MpServer', x=-143.45, y=72.00, z=388.55], EntityCow['Cow'/55, l='MpServer', x=-146.50, y=73.00, z=387.50], EntityBat['Bat'/57, l='MpServer', x=-145.00, y=32.81, z=450.20], EntityCow['Cow'/60, l='MpServer', x=-140.65, y=73.00, z=414.15], EntityCow['Cow'/61, l='MpServer', x=-131.51, y=74.00, z=415.49], EntityCow['Cow'/62, l='MpServer', x=-142.18, y=73.00, z=415.48], EntityCow['Cow'/63, l='MpServer', x=-133.83, y=72.00, z=408.51], EntityCreeper['Creeper'/65, l='MpServer', x=-141.50, y=30.00, z=447.50], EntityCow['Cow'/67, l='MpServer', x=-126.81, y=72.00, z=440.50], EntityCow['Cow'/68, l='MpServer', x=-132.20, y=71.00, z=445.58], EntityCow['Cow'/69, l='MpServer', x=-129.50, y=71.00, z=443.50], EntityBat['Bat'/325, l='MpServer', x=0.53, y=19.07, z=484.86], EntitySheep['Sheep'/70, l='MpServer', x=-133.53, y=72.00, z=438.77], EntitySheep['Sheep'/71, l='MpServer', x=-126.69, y=72.00, z=434.77], EntityBat['Bat'/329, l='MpServer', x=-46.75, y=47.10, z=507.75], EntitySheep['Sheep'/78, l='MpServer', x=-122.82, y=71.00, z=439.82], EntityCow['Cow'/79, l='MpServer', x=-126.63, y=72.00, z=432.80], EntitySheep['Sheep'/80, l='MpServer', x=-129.19, y=72.00, z=439.27], EntitySheep['Sheep'/337, l='MpServer', x=8.21, y=69.00, z=452.56], EntitySheep['Sheep'/338, l='MpServer', x=7.24, y=70.00, z=450.62], EntityPig['Pig'/90, l='MpServer', x=-104.50, y=69.09, z=381.50], EntityPig['Pig'/91, l='MpServer', x=-106.57, y=71.00, z=386.37], EntityPig['Pig'/92, l='MpServer', x=-110.50, y=71.00, z=385.50], EntityZombie['Zombie'/93, l='MpServer', x=-101.50, y=22.00, z=427.50], EntityZombie['Zombie'/94, l='MpServer', x=-102.50, y=22.00, z=427.50], EntityPig['Pig'/95, l='MpServer', x=-107.25, y=72.00, z=425.21], EntityPig['Pig'/96, l='MpServer', x=-98.32, y=72.00, z=428.24], EntityPig['Pig'/97, l='MpServer', x=-109.31, y=72.00, z=432.23], EntitySkeleton['Skeleton'/865, l='MpServer', x=-100.27, y=43.00, z=497.53], EntitySkeleton['Skeleton'/866, l='MpServer', x=-100.50, y=42.00, z=498.50], EntityCreeper['Creeper'/869, l='MpServer', x=-8.50, y=49.00, z=408.50], EntityCreeper['Creeper'/870, l='MpServer', x=-5.50, y=49.00, z=407.50], EntitySkeleton['Skeleton'/872, l='MpServer', x=-9.32, y=52.75, z=405.30], EntityPig['Pig'/107, l='MpServer', x=-81.50, y=71.00, z=398.50], EntityPig['Pig'/108, l='MpServer', x=-80.72, y=70.00, z=391.13], EntityPig['Pig'/109, l='MpServer', x=-87.78, y=71.00, z=399.63], EntityZombie['Zombie'/110, l='MpServer', x=-86.50, y=41.00, z=423.50], EntityPig['Pig'/111, l='MpServer', x=-82.73, y=72.00, z=419.43], EntityPig['Pig'/113, l='MpServer', x=-67.75, y=70.00, z=388.62], EntityPig['Pig'/114, l='MpServer', x=-78.46, y=71.00, z=396.74], EntityZombie['Zombie'/373, l='MpServer', x=-25.50, y=10.00, z=449.50], EntityZombie['Zombie'/118, l='MpServer', x=-35.44, y=19.82, z=395.70], EntitySpider['Spider'/374, l='MpServer', x=-28.50, y=10.00, z=449.50], EntitySkeleton['Skeleton'/119, l='MpServer', x=-35.31, y=44.00, z=389.50], EntityZombie['Zombie'/887, l='MpServer', x=-139.50, y=30.00, z=453.50], EntitySkeleton['Skeleton'/120, l='MpServer', x=-45.50, y=50.00, z=388.21], EntityZombie['Zombie'/888, l='MpServer', x=-142.50, y=30.00, z=449.50], EntityBat['Bat'/121, l='MpServer', x=-44.58, y=31.10, z=402.43], EntitySheep['Sheep'/122, l='MpServer', x=-47.52, y=62.00, z=436.76], EntitySheep['Sheep'/123, l='MpServer', x=-52.17, y=65.00, z=434.40], EntitySheep['Sheep'/124, l='MpServer', x=-42.52, y=66.00, z=432.77], EntitySheep['Sheep'/125, l='MpServer', x=-45.50, y=65.00, z=438.50], EntitySkeleton['Skeleton'/145, l='MpServer', x=-7.50, y=24.00, z=399.50], EntityBat['Bat'/662, l='MpServer', x=-46.55, y=58.10, z=379.40], EntityZombie['Zombie'/920, l='MpServer', x=-91.40, y=23.00, z=358.55], EntityZombie['Zombie'/921, l='MpServer', x=-87.79, y=23.00, z=353.68], EntityZombie['Zombie'/922, l='MpServer', x=-94.50, y=23.00, z=358.50], EntityZombie['Zombie'/923, l='MpServer', x=-94.47, y=23.00, z=361.42], EntitySkeleton['Skeleton'/157, l='MpServer', x=7.50, y=34.00, z=419.50], EntityCreeper['Creeper'/159, l='MpServer', x=4.13, y=50.00, z=431.31], EntitySheep['Sheep'/161, l='MpServer', x=0.81, y=70.00, z=444.96], EntitySkeleton['Skeleton'/930, l='MpServer', x=-35.50, y=22.00, z=506.50], EntityItem['item.item.reeds'/419, l='MpServer', x=-33.71, y=63.00, z=471.37], EntityZombie['Zombie'/931, l='MpServer', x=-37.50, y=22.00, z=506.50], EntityItem['item.item.reeds'/420, l='MpServer', x=-34.88, y=63.00, z=470.89], EntityCreeper['Creeper'/438, l='MpServer', x=-60.50, y=23.00, z=461.50], EntitySquid['Squid'/958, l='MpServer', x=-73.59, y=64.00, z=430.01], EntityCreeper['Creeper'/708, l='MpServer', x=-66.68, y=41.00, z=419.23], EntityZombie['Zombie'/248, l='MpServer', x=-84.19, y=21.00, z=507.85], EntityZombie['Zombie'/251, l='MpServer', x=-89.50, y=17.00, z=455.76], EntityZombie['Zombie'/252, l='MpServer', x=-94.50, y=19.00, z=474.50], EntityZombie['Zombie'/253, l='MpServer', x=-92.50, y=19.00, z=468.50], EntitySkeleton['Skeleton'/509, l='MpServer', x=-1.46, y=16.00, z=507.74], EntitySheep['Sheep'/254, l='MpServer', x=-83.52, y=89.00, z=486.95], EntitySheep['Sheep'/255, l='MpServer', x=-83.78, y=88.00, z=484.64]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-140-generic
	Java Version: 1.8.0_282, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 916504072 bytes (874 MB) / 1669332992 bytes (1592 MB) up to 3750756352 bytes (3577 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4024m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version        | Source                                  | Signature                                |
	|:------ |:--------- |:-------------- |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2         | minecraft.jar                           | None                                     |
	| LCHIJA | mcp       | 9.42           | minecraft.jar                           | None                                     |
	| LCHIJA | FML       | 8.0.99.99      | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2855   | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | dupemod   | 1.7            | DupeMod-1.12.2-1.7.jar                  | None                                     |
	| LCHIJA | forgelin  | 1.8.4          | Forgelin-1.8.4.jar                      | None                                     |
	| LCHIJA | squidmilk | 1.12.2-2.0.0.0 | squidmilk-1.12.2-2.0.0.0.jar            | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0 NVIDIA 340.108' Renderer: 'GeForce 9400 GT/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce 9400 GT/PCIe/SSE2 GL version 3.3.0 NVIDIA 340.108, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU G620 @ 2.60GHz

**Comment by DeflatedPickle** [comment]
Completely my bad, sorry. I've figured out what was wrong and will have new builds for all the versions soon
